import Head from "next/head";

import { Inter } from "next/font/google";
import Header from "@/components/Header";

import Nav from "@/components/Nav";
import Results from "@/components/Results";

export default function Home() {
  return (
    <>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />
      <Results />
    </>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;
}
