import Head from "next/head";

import { Inter } from "next/font/google";
import Header from "@/components/Header";
import requests from "@/utils/requests";

import Nav from "@/components/Nav";
import Results from "@/components/Results";

export default function Home({ results }) {
  return (
    <>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />
      <Results results={results} />
    </>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;

  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then((res) => res.json());

  return {
    props: {
      results: request.results,
    },
  };
}
